version: "3.7"
services:
  postgres_db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
    - "5432:5432"

  web:
    container_name: practica-ci
    image: practica-ci
    build: ./
    depends_on:
      - postgres_db
    ports:
      - "8080:8080"